version: "3"
services:
  funding-gateway-api-replica:
    # replace username/repo:tag with your name and image details
    image: gcr.io/cf247-altostratus/{imagetag}
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "30"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "5004:80"
    networks:
      - carfinancenet
networks:
  carfinancenet: